### ISSUE TITLE
iOS 13.4 Compatibility Issue with lottie-ios

### ISSUE THREAD

**Issue by denysoleksiienko** [lottie-react-native/lottie-react-native#1386]
### Description

**Environment**:

- iOS Minimum Deployment Target: 13.4
- lottie-react-native: 7.2.2 (initially), tried 6.5.1 and 5.1.6
- lottie-ios: 4.5.0 (initially), tried 4.2.0 and 3.4.4
- React Native: 0.78+
- Xcode: Xcode 26.1
- New Architecture: Enabled (RCT_NEW_ARCH_ENABLED = '1')

**Problem**:
I'm trying to implement a custom Lottie splash screen for my React Native app with minimum iOS deployment target of 13.4. However, I'm getting the following compilation error:
```
Compiling for iOS 13.4, but module 'Lottie' has a minimum deployment target of iOS 15.1: 
/Users/mac/Library/Developer/Xcode/DerivedData/mobileapp-cngxwxwwcykwmddmlojirosldrfg/Index.noindex/Build/Products/Debug-iphonesimulator/lottie-ios/Lottie.framework/Modules/Lottie.swiftmodule/arm64-apple-ios-simulator.swiftmodule
```

What I've Tried
Attempt 1: Using lottie-react-native 7.2.2
"lottie-react-native": "7.2.2"
Podfile:
```
rubypod 'lottie-ios', '4.5.0'
Result: Error - lottie-ios 4.5.0 requires iOS 15.1+
```

Attempt 2: Downgrading to lottie-react-native 6.5.1
"lottie-react-native": "6.5.1"
Podfile: (no explicit lottie-ios specified)
Result: Still getting the same error about iOS 15.1 requirement

Attempt 3: Using lottie-react-native 5.1.6
"lottie-react-native": "5.1.6"
Podfile: (no explicit lottie-ios specified)
Podfile.lock shows:
```
ruby- lottie-ios (3.4.4)
- lottie-react-native (5.1.6):
  - lottie-ios (~> 3.4.0)
```
Result: Still the same error, even though lottie-ios 3.4.4 officially supports iOS 11.0+

Current Podfile:

```
# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

ENV['RCT_NEW_ARCH_ENABLED'] = '1'

target 'MobileApp' do
  $RNFirebaseAsStaticFramework = true
  $RNFirebaseAnalyticsEnableAdSupport = true

  config = use_native_modules!

  # use_frameworks static! is required Google Firebase
  use_frameworks! :linkage => :static

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'lottie-ios', '4.5.0'

  target 'MobileAppStaging' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
```

Custom SplashScreen Implementation
I've created a custom native module for displaying Lottie animations during app launch. Here are both versions for different lottie-ios versions:
Version 1: For lottie-ios 4.x (LottieAnimationView)
```
import UIKit
import React
import Lottie

@objc(SplashScreen)
public class SplashScreen: NSObject, RCTBridgeModule {

    public enum ResizeMode: String {
        case cover       // scaleAspectFill
        case contain     // scaleAspectFit
        case stretch     // scaleToFill
        case center      // center
    }

    private static var forceToCloseByHideMethod = false
    private static var loadingView: UIView?
    private static var window: UIWindow?
    private static var isAnimationFinished = false
    private static var resizeMode: ResizeMode = .contain
    
    public static func moduleName() -> String! {
        return "SplashScreen"
    }
    
    public func methodQueue() -> DispatchQueue! {
        return DispatchQueue.main
    }

    // MARK: - PUBLIC API
    @objc public static func setupLottieSplash(
        in window: UIWindow?,
        lottieName: String,
        backgroundColor: UIColor = .white,
        forceToCloseByHideMethod: Bool = false,
        resizeMode: String = "contain"
    ) {
        guard
            let rootVC = window?.rootViewController,
            let rootView = rootVC.view
        else { return }

        self.window = window
        self.forceToCloseByHideMethod = forceToCloseByHideMethod
        self.isAnimationFinished = false
        self.resizeMode = ResizeMode(rawValue: resizeMode) ?? .contain

        rootView.backgroundColor = backgroundColor

        let animationView = LottieAnimationView(name: lottieName)
        animationView.frame = rootView.bounds
        animationView.center = rootView.center
        animationView.backgroundColor = backgroundColor

        switch self.resizeMode {
        case .cover:
            animationView.contentMode = .scaleAspectFill
            animationView.clipsToBounds = true
        case .contain:
            animationView.contentMode = .scaleAspectFit
        case .stretch:
            animationView.contentMode = .scaleToFill
        case .center:
            animationView.contentMode = .center
        }

        showLottieSplash(animationView, inRootView: rootView)
    }

    @objc private static func showLottieSplash(_ animationView: UIView, inRootView rootView: UIView) {
        loadingView = animationView
        isAnimationFinished = false

        rootView.addSubview(animationView)
        rootView.bringSubviewToFront(animationView)
        animationView.layer.zPosition = 9999

        window?.windowLevel = UIWindow.Level.alert + 1

        if let lottieView = animationView as? LottieAnimationView {
            lottieView.play { _ in
                DispatchQueue.main.async {
                    self.isAnimationFinished = true
                    hideSplashScreen()
                }
            }
        } else {
            DispatchQueue.main.asyncAfter(deadline: .now() + 0.1) {
                self.isAnimationFinished = true
                hideSplashScreen()
            }
        }
    }

    @objc public static func hide() {
        if forceToCloseByHideMethod {
            hideSplashScreen()
        }
    }

    private static func hideSplashScreen() {
        guard let loadingView = loadingView else { return }

        UIView.animate(withDuration: 0.2, animations: {
            loadingView.alpha = 0
        }, completion: { _ in
            loadingView.removeFromSuperview()
            self.loadingView = nil
            window?.windowLevel = .normal
        })
    }

    @objc public static func jsLoadError(_ notification: Notification) {
        hideSplashScreen()
    }

    @objc public func hide() {
        SplashScreen.hide()
    }
}

extension SplashScreen {
    @objc public static func requiresMainQueueSetup() -> Bool {
        return true
    }
}
```

Version 2: For lottie-ios 3.x (AnimationView)

```
import UIKit
import React
import Lottie

@objc(SplashScreen)
public class SplashScreen: NSObject, RCTBridgeModule {

    public enum ResizeMode: String {
        case cover
        case contain
        case stretch
        case center
    }

    private static var forceToCloseByHideMethod = false
    private static var loadingView: UIView?
    private static var window: UIWindow?
    private static var isAnimationFinished = false
    private static var resizeMode: ResizeMode = .contain
    
    public static func moduleName() -> String! {
        return "SplashScreen"
    }
    
    public func methodQueue() -> DispatchQueue! {
        return DispatchQueue.main
    }

    @objc public static func setupLottieSplash(
        in window: UIWindow?,
        lottieName: String,
        backgroundColor: UIColor = .white,
        forceToCloseByHideMethod: Bool = false,
        resizeMode: String = "contain"
    ) {
        guard
            let rootVC = window?.rootViewController,
            let rootView = rootVC.view
        else { return }

        self.window = window
        self.forceToCloseByHideMethod = forceToCloseByHideMethod
        self.isAnimationFinished = false
        self.resizeMode = ResizeMode(rawValue: resizeMode) ?? .contain

        rootView.backgroundColor = backgroundColor

        // Note: AnimationView instead of LottieAnimationView for 3.x
        let animationView = AnimationView(name: lottieName)
        animationView.frame = rootView.bounds
        animationView.center = rootView.center
        animationView.backgroundColor = backgroundColor

        switch self.resizeMode {
        case .cover:
            animationView.contentMode = .scaleAspectFill
            animationView.clipsToBounds = true
        case .contain:
            animationView.contentMode = .scaleAspectFit
        case .stretch:
            animationView.contentMode = .scaleToFill
        case .center:
            animationView.contentMode = .center
        }

        showLottieSplash(animationView, inRootView: rootView)
    }

    @objc private static func showLottieSplash(_ animationView: UIView, inRootView rootView: UIView) {
        loadingView = animationView
        isAnimationFinished = false

        rootView.addSubview(animationView)
        rootView.bringSubviewToFront(animationView)
        animationView.layer.zPosition = 9999

        window?.windowLevel = UIWindow.Level.alert + 1

        // Note: AnimationView instead of LottieAnimationView for 3.x
        if let lottieView = animationView as? AnimationView {
            lottieView.play { _ in
                DispatchQueue.main.async {
                    self.isAnimationFinished = true
                    hideSplashScreen()
                }
            }
        } else {
            DispatchQueue.main.asyncAfter(deadline: .now() + 0.1) {
                self.isAnimationFinished = true
                hideSplashScreen()
            }
        }
    }

    @objc public static func hide() {
        if forceToCloseByHideMethod {
            hideSplashScreen()
        }
    }

    private static func hideSplashScreen() {
        guard let loadingView = loadingView else { return }

        UIView.animate(withDuration: 0.2, animations: {
            loadingView.alpha = 0
        }, completion: { _ in
            loadingView.removeFromSuperview()
            self.loadingView = nil
            window?.windowLevel = .normal
        })
    }

    @objc public static func jsLoadError(_ notification: Notification) {
        hideSplashScreen()
    }

    @objc public func hide() {
        SplashScreen.hide()
    }
}

extension SplashScreen {
    @objc public static func requiresMainQueueSetup() -> Bool {
        return true
    }
}
```

Steps Taken to Debug
1. Completely cleaned Xcode DerivedData: rm -rf ~/Library/Developer/Xcode/DerivedData
2. Cleaned pods: cd ios && rm -rf Pods Podfile.lock build && pod cache clean --all && pod install
3. Verified in Xcode Build Settings that iOS Deployment Target is set to 13.4 for both main target and lottie-ios pod
4. Added post_install script to force deployment target
5. Tried multiple versions of both lottie-react-native and lottie-ios

Questions
1. Why is the compiled module showing iOS 15.1 requirement when Podfile.lock shows lottie-ios (3.4.4) which supports iOS 11.0+?
2. Is there a caching issue in Xcode that's not being cleared properly?
3. Could this be related to React Native's New Architecture (RCT_NEW_ARCH_ENABLED = '1')?
4. Is there a known working combination of lottie-react-native and lottie-ios versions for iOS 13.4?

Expected Behavior
The app should compile successfully with lottie-ios on iOS 13.4 minimum deployment target.
Actual Behavior
Getting compilation error stating module requires iOS 15.1+, even when using lottie-ios 3.4.4 which officially supports iOS 11.0+.

Additional Context
- Using use_frameworks! :linkage => :static for Firebase compatibility
- Project uses React Native New Architecture
- Other dependencies compile fine with iOS 13.4 target

Any help would be greatly appreciated!

### Steps to reproduce

-

### Snack or a link to a repository

-

### Lottie React Native version

7.2.2, 6.5.1, 5.1.6

### React Native version

0.79.5

### Platforms

iOS

### Workflow

React Native

### Architecture

Fabric (New Architecture)

### Build type

None

### Device

None

### Acknowledgements

Yes
