### ISSUE TITLE
Unable to build with React Native 0.61

### ISSUE THREAD

**Issue by NathanSaunders01** [lottie-react-native/lottie-react-native#575]
### Description

Installed lottie-react-native into our react native project. Although we're using RN 0.61, we were unable follow the latest steps so had to add them in manually.

We have added both packages to our package.json file and added the following lines to our Podfile

`pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'`
`pod 'lottie-ios', '~> 3.1.3'`

When we build, we get the following errors: 

```
Undefined symbols for architecture x86_64:
  "_swift_getFunctionReplacement", referenced from:
      _swift_getFunctionReplacement50 in libswiftCompatibilityDynamicReplacements.a(DynamicReplaceable.cpp.o)
     (maybe you meant: _swift_getFunctionReplacement50)
  "_swift_getOrigOfReplaceable", referenced from:
      _swift_getOrigOfReplaceable50 in libswiftCompatibilityDynamicReplacements.a(DynamicReplaceable.cpp.o)
     (maybe you meant: _swift_getOrigOfReplaceable50)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by lnanhkhoa** [comment]
you need to create File Swift Bridging header. 
here: https://stackoverflow.com/questions/37268368/swift-bridging-header-file-wont-work-with-use-frameworks

**Comment by zsaraf** [comment]
^^ That doesn't fix it for me. Any other ideas?

**Comment by lnanhkhoa** [comment]
> ^^ That doesn't fix it for me. Any other ideas?
can you show it to me? Have you run `pod install` again.
 My project use: 
```
"lottie-ios": "3.0.3",
"lottie-react-native": "3.1.1"
```
my `ios/` folder have 2 files: `File.swift` and `${projectName}-Bridging-Header.h` after that.

**Comment by valentinjob** [comment]
I have the same issue. Build works fine but have this issue when try to create an archive. 
Swift file and bridge header already created. Tried to use the latest version and the one that in the post above.

**Comment by egeondundee** [comment]
I have the same issue too.

**Comment by egeondundee** [comment]
I solved the problem in that way. 
1. `yarn add lottie-react-native
yarn add lottie-ios@3.1.3`
2. pod install (in the ios folder of course) 
3. open .xcworkspace file 
4. [
<img width="271" alt="Schermata 2019-10-12 alle 13 15 10" src="https://user-images.githubusercontent.com/37193302/66700596-61e2b900-ecf2-11e9-930a-038694edf7c0.png">
]
5. Create new Swift File (remember the targets) 
<img width="354" alt="Schermata 2019-10-12 alle 13 16 31" src="https://user-images.githubusercontent.com/37193302/66700600-876fc280-ecf2-11e9-82e2-4defb2c89da4.png">
6. It will automatically appear this view -> Specify "Create Bridging Header". 
<img width="549" alt="Schermata 2019-10-12 alle 13 17 08" src="https://user-images.githubusercontent.com/37193302/66700604-9bb3bf80-ecf2-11e9-993d-d5965aff5415.png">
7. Go to your project Build Settings, you should see those stuffs. 
<img width="1211" alt="Schermata 2019-10-12 alle 13 18 53" src="https://user-images.githubusercontent.com/37193302/66700635-fcdb9300-ecf2-11e9-9073-2d118aa49da4.png">
8. Clean your project and run 

> react-native run-ios

**Comment by roubo** [comment]
> I solved the problem in that way.
> 
> 1. `yarn add lottie-react-native`
>    `yarn add lottie-ios@3.1.3`
> 2. _pod install_ (in the ios folder of course)
> 3. open **.xcworkspace** file
> 4. Select your project folder
> 
> <img alt="Schermata 2019-10-12 alle 13 15 10" width="271" src="https://user-images.githubusercontent.com/37193302/66700596-61e2b900-ecf2-11e9-930a-038694edf7c0.png">
> 
> 1. Create new **Swift File** (remember the targets)
> 
> <img alt="Schermata 2019-10-12 alle 13 16 31" width="354" src="https://user-images.githubusercontent.com/37193302/66700600-876fc280-ecf2-11e9-82e2-4defb2c89da4.png">
> 
> 6. It will automatically appear this view -> Specify "Create Bridging Header".
> <img alt="Schermata 2019-10-12 alle 13 17 08" width="549" src="https://user-images.githubusercontent.com/37193302/66700604-9bb3bf80-ecf2-11e9-993d-d5965aff5415.png">
> 
> 7. Go to your project Build Settings, you should see those stuffs.
> <img alt="Schermata 2019-10-12 alle 13 18 53" width="1211" src="https://user-images.githubusercontent.com/37193302/66700635-fcdb9300-ecf2-11e9-9073-2d118aa49da4.png">
> 
> 8. Clean your project and run
> > react-native run-ios

**AND ADD THIS WORK FOR ME：**

remove "Library search paths" $(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)
OR/AND
remove "Library search paths" $(TOOLCHAIN_DIR)/usr/lib/swift5.0/$(PLATFORM_NAME)

**Comment by kromsik** [comment]
This does't work for me. This is ok during my Dev environment with Simulator. But when it comes to build I face an error `Failed to emit precompiled header for bridging header`

**Comment by kromsik** [comment]
With this done I still have
`error: failed to emit precompiled header '/Users/jenkins/Library/Developer/Xcode/DerivedData/project-hdrnxcgynoavyidfanqgvrcyhija/Build/Intermediates.noindex/ArchiveIntermediates/project/PrecompiledHeaders/project-Bridging-Header-swift_7F1TIZ8QSEQW-clang_TTMMHC9KMDGA.pch' for bridging header '/Users/jenkins/build/workspace/mobile-client-ios/ios/project-Bridging-Header.h'`

**Comment by DCKT** [comment]
I have the same issue as @kromsik  
I have some extra fields btw
<img width="540" alt="Capture d’écran 2019-10-28 à 11 18 29" src="https://user-images.githubusercontent.com/1548421/67670663-af0e8e00-f974-11e9-8194-913dbd6de82a.png">

**Comment by jmy10241024** [comment]
@DCKT  It doesn't matter, just clean and build your project. It will  work.

**Comment by WillVill** [comment]
@roubo 

This was the culprit:

```
remove "Library search paths" $(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)
OR/AND
remove "Library search paths" $(TOOLCHAIN_DIR)/usr/lib/swift5.0/$(PLATFORM_NAME)
```

**Comment by suwu150** [comment]
I added another step to the subordinate step。
```
"$(TOOLCHAIN_DIR)/usr/lib/swift5.0/$(PLATFORM_NAME)"
```

Simultaneously，set  *Dead Code Stripping* to *YES*
![image](https://user-images.githubusercontent.com/20339760/72504961-ddb44a80-3879-11ea-8c6f-571b63b8d8d2.png)

This  work for me

**Comment by Abhijeetjaiswalit** [comment]
@suwu150 we need to add this too ?

`"$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)"`

**Comment by suwu150** [comment]
@

> @suwu150 we need to add this too ?
> 
> `"$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)"`

I can run after adding！

**Comment by lopesrichard** [comment]
@enzomanuelmangano this works to me on 0.61.5

**Comment by ckOfor** [comment]
https://stackoverflow.com/a/61627331/10355668

**Comment by bhirmbani** [comment]
> > I solved the problem in that way.
> > 
> > 1. `yarn add lottie-react-native`
> >    `yarn add lottie-ios@3.1.3`
> > 2. _pod install_ (in the ios folder of course)
> > 3. open **.xcworkspace** file
> > 4. Select your project folder
> > 
> > <img alt="Schermata 2019-10-12 alle 13 15 10" width="271" src="https://user-images.githubusercontent.com/37193302/66700596-61e2b900-ecf2-11e9-930a-038694edf7c0.png">
> > 
> > 1. Create new **Swift File** (remember the targets)
> > 
> > <img alt="Schermata 2019-10-12 alle 13 16 31" width="354" src="https://user-images.githubusercontent.com/37193302/66700600-876fc280-ecf2-11e9-82e2-4defb2c89da4.png">
> > 
> > 1. It will automatically appear this view -> Specify "Create Bridging Header".
> > 
> > <img alt="Schermata 2019-10-12 alle 13 17 08" width="549" src="https://user-images.githubusercontent.com/37193302/66700604-9bb3bf80-ecf2-11e9-993d-d5965aff5415.png">
> > 
> > 1. Go to your project Build Settings, you should see those stuffs.
> > 
> > <img alt="Schermata 2019-10-12 alle 13 18 53" width="1211" src="https://user-images.githubusercontent.com/37193302/66700635-fcdb9300-ecf2-11e9-9073-2d118aa49da4.png">
> > 
> > 1. Clean your project and run
> > 
> > > react-native run-ios
> 
> **AND ADD THIS WORK FOR ME：**
> 
> remove "Library search paths" $(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)
> OR/AND
> remove "Library search paths" $(TOOLCHAIN_DIR)/usr/lib/swift5.0/$(PLATFORM_NAME)

I did the last line.. this work for me too
