### ISSUE TITLE
method setAnimationFromJson in class LottieAnimationView cannot be applied to given types

### ISSUE THREAD

**Issue by spsaucier** [lottie-react-native/lottie-react-native#543]
### Description
```
import React from 'react';
import LottieView from 'lottie-react-native';

function Spinner() {
  // eslint-disable-next-line global-require
  return <LottieView source={require('./loading.json')} autoPlay loop />;
}
export default Spinner;
```

Begets:
```
node_modules/lottie-react-native/src/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewPropertyManager.java:93: error: method setAnimationFromJson in class LottieAnimationView cannot be applied to given types;
      view.setAnimationFromJson(animationJson, Integer.toString(animationJson.hashCode()));
          ^
  required: String
  found: String,String
  reason: actual and formal argument lists differ in length
Note: /Users/stephensaucier/cfa/cowponents-native/node_modules/lottie-react-native/src/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewManager.java uses unchecked or unsafe operations.
```

### Steps to Reproduce

1. Run `yarn android`

**Expected behavior:**
Build completes successfully, app launches successfully

**Actual behavior:**
Build fails with above error message.

### Versions
`"lottie-react-native": "3.1.0",`
`"react": "16.8.6",`
`"react-native": "0.60.4",`

**Comment by spsaucier** [comment]
Appears to work correctly in `3.0.3`

**Comment by anniewey** [comment]
Still seeing in `3.2.1`. The issue starts appearing after `3.0.4`

**Comment by ifero** [comment]
Is there any chance to fix this problem? I've updated from RN 0.59 to 0.61 and I'm completely stuck on this.

**Comment by jegathispandi** [comment]
> Still seeing in `3.2.1`. The issue starts appearing after `3.0.4`

yes I am also facing this issue

**Comment by ifero** [comment]
I've downgraded to `3.0.3` since `3.0.4` has upgraded `lottie-android` version. What I don't get is that the weak reference of the `LottieAnimationView` seems to not have any reference of `setAnimationFromJson`

In `LottieAnimationViewPropertyManager.java`
```
public void commitChanges() {
    LottieAnimationView view = viewWeakReference.get();
    if (view == null) {
      return;
    }

    if (animationJson != null) {
      view.setAnimationFromJson(animationJson, Integer.toString(animationJson.hashCode())); 
       ^^^^^^
       here is the problem.

      animationJson = null;
    }
```

but if we look at the `lottie-android` sdk `v2.5.6` `seAnimationFromJson(arg1, arg2)` does not exist. this is why from `3.0.4` it does explodes but what I don't get is how it does crash also in latest `lottie-react-native` version with the same error

**Comment by jegathispandi** [comment]
"react": "16.9.0",
    "react-native": "0.60.5",
"lottie-ios": "^3.0.3",
    "lottie-react-native": "3.0.3",


This is my package.json. but still i am facing this issue

**Comment by rowinbot** [comment]
Is there any fix to this issue?

**Comment by mailyokesh** [comment]
Seeing a crash only in android. I am in the latest version both react-native as well as lottie. I see the same crash while trying to play json lottie animation. Same json works fine in iOS. We were using an older version of lottie and upgraded to the latest due to react native version upgrade. Same json has been working in older versions. 

Json file used to play lottie animation: [SpinBtnHilite copy.json.txt](https://github.com/react-native-community/lottie-react-native/files/3853115/SpinBtnHilite.copy.json.txt)

Version where it started crashing:
"react": "16.9.0",
"react-native": "0.61.4",
"lottie-ios": "3.1.3",
"lottie-react-native": "^3.3.1",

version where the same json was working:
"react-native": "0.59.10",
"react": "16.8.3",
"lottie-react-native": "^2.6.1",

Here is the run time error message while running in pixel3a phone. 
11-15 14:50:14.856 32282 32282 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method setAnimationFromJson(Ljava/lang/String;Ljava/lang/String;)V in class Lcom/airbnb/lottie/LottieAnimationView; or its super classes (declaration of 'com.airbnb.lottie.LottieAnimationView' appears in /data/app/com.windcreek.app-QmQfBD37KG_tazS1LulgiA==/base.apk!classes2.dex)
11-15 14:50:14.856 32282 32282 E AndroidRuntime: 	at com.airbnb.android.react.lottie.LottieAnimationViewPropertyManager.commitChanges(LottieAnimationViewPropertyManager.java:103)
11-15 14:50:14.856 32282 32282 E AndroidRuntime: 	at com.airbnb.android.react.lottie.LottieAnimationViewManager.onAfterUpdateTransaction(LottieAnimationViewManager.java:224)
11-15 14:50:14.856 32282 32282 E AndroidRuntime: 	at com.airbnb.android.react.lottie.LottieAnimationViewManager.onAfterUpdateTransaction(LottieAnimationViewManager.java:27)
11-15 14:50:14.856 32282 32282 E AndroidRuntime: 	at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:50)
11-15 14:50:14.856 32282 32282 E AndroidRuntime: 	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:278)
11-15 14:50:14.856 32282 32282 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:179)
11-15 14:50:14.856 32282 32282 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.j

**Comment by mailyokesh** [comment]
i also tried to downgrade to 3.0.3, still the same crash. Also since our app has to be on "react-native": "0.61.4" we cannot downgrade to any older version of lottie. Does anyone knows of a fix for this? due to this we are not able to release our app.

**Comment by ifero** [comment]
"react": "16.9.0",
"react-native": "0.61.4",
"lottie-ios": "3.0.3",
"lottie-react-native": "3.0.3",

This is my configuration and it is working fine. Of course this is not fixing the problem but at least its working

**Comment by mailyokesh** [comment]
@ifero is it working fine in android for you with the downgraded versions?

**Comment by AaronTon** [comment]
“ react”：“ 16.9.0”，
“ react-native”：“ 0.61.5”，
“ lottie-ios”：“ 3.1.3”，
“ lottie-react-native”：“ 3.2.1”，

This is my configuration and it is working fine.
